name: Build and Package Go Application

on: [push]

jobs:
  build-and-package:
    name: Build and Package
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
                goarch: [amd64, arm64]
goos: [linux]
        include:
          - goarch: amd64
            debArch: amd64
          - goarch: arm64
            debArch: arm64
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17' # Adjust as needed for your Go version requirements
    
    - name: Build Binary
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-X 'main.GitCommitHash=${{ github.sha }}'" -v -o github-replica-${{ matrix.goarch }} github_replica.go
    
    - name: Install Packaging Tools
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev
    
    - name: Prepare Debian Package Structure
      run: |
        mkdir -p github-replica-${{ matrix.goarch }}/DEBIAN
        echo "Package: github-replica
Version: ${{ github.sha }}
Section: base
Priority: optional
Architecture: ${{ matrix.debArch }}
Depends: libc6 (>= 2.7)
Maintainer: Matt Brocklehurst <m@xor.me.uk>
Description: GitHub Replica Application" > github-replica-${{ matrix.goarch }}/DEBIAN/control
    
    - name: Copy Binary to Package Structure
      run: |
        mkdir -p github-replica-${{ matrix.goarch }}/usr/local/bin
        cp ./github-replica-${{ matrix.goarch }} github-replica-${{ matrix.goarch }}/usr/local/bin/github-replica
    
    - name: Build Debian Package
      run: |
        dpkg-deb --build github-replica-${{ matrix.goarch }}
        mv github-replica-${{ matrix.goarch }}.deb github-replica-${{ matrix.goarch }}-${{ github.sha }}.deb
    
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: github-replica-binary-${{ matrix.goarch }}
        path: ./github-replica-${{ matrix.goarch }}
    
    - name: Upload .deb Package
      uses: actions/upload-artifact@v2
      with:
        name: github-replica-${{ matrix.goarch }}-${{ github.sha }}.deb
        path: ./github-replica-${{ matrix.goarch }}-${{ github.sha }}.deb
