name: Build and Artifact Go Binaries

on: [push]

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        goarch: [amd64, arm64]
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17' # Adjust as needed for your Go version requirements
    
    - name: Build Binary
      env:
        GOARCH: ${{ matrix.goarch }}
      run: |
        GOOS=linux GOARCH=${GOARCH} go build -v -o checkout_all_repo_${GOARCH} checkout_all_repo.go
      
    - name: Archive Binary
      uses: actions/upload-artifact@v2
      with:
        name: checkout_all_repo-${{ matrix.goarch }}
        path: ./checkout_all_repo_${{ matrix.goarch }}